name: adt_annotation
description: A simple command-line application.
version: 2.0.2
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0-154.0.dev <3.0.0'


dependencies:
  utils: ^3.0.0

dev_dependencies:
  lints: ^1.0.0
