name: example
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0-154.0.dev <3.0.0'


dependencies:
  adt_annotation: ^1.0.1

dev_dependencies:
  lints: ^1.0.0
  build_runner:
  adt_generator: 

dependency_overrides:
  adt_generator:
    path: ../adt_generator
