name: adt_annotation_base
description: DO NOT USE. Base for adt_annotations
homepage: https://github.com/kalildev/algebraic_data_types
version: 3.0.2

environment:
  sdk: '>=2.16.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
