name: adt_generator
description: A simple command-line application.
version: 3.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
  adt_annotation: ^3.0.3
  source_gen: ^1.2.0
  build: ^2.3.0
  build_config: ^1.0.0
  analyzer: ^4.0.0

dev_dependencies:
  lints: ^1.0.0
