name: adt_generator
description: The generator for algebraic data types.
version: 3.0.2
homepage: https://github.com/kalildev/algebraic_data_types

environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
  adt_annotation_base: ^3.0.2
  source_gen: ^1.2.0
  build: ^2.3.0
  build_config: ^1.0.0
  analyzer: ^4.0.0

dev_dependencies:
  lints: ^1.0.0
