name: adt_annotations
description: An algebraic data type library (annotations)
version: 3.0.3

environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
  utils: ^3.0.4
  adt_annotation_base: 3.0.2

dev_dependencies:
  lints: ^1.0.0
